---
copyright: '&copy; 2015-2024'
extra:
  dictionary_app_root: /apps/dictionary
  dictionary_viewer_page_id: Viewer
  encyclopedia_entries_page_title: EncyclopediaEntries
  encyclopedia_page_title: Encyclopedia
  nav_exclude:
    - EncyclopediaEntries
  project_description: GDC Docs
  project_org: GDC
  project_root_dir: /
  version: 1.0
  analytics:
    provider: custom
extra_css:
  - stylesheets/gdc-common.css
  - stylesheets/homepage.css
  - stylesheets/font-awesome-4.5.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      combine_header_slug: true
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - attr_list

nav:
  - Home: index.md
  - API:
      - Getting Started: API/Users_Guide/Getting_Started.md
      - Search and Retrieval: API/Users_Guide/Search_and_Retrieval.md
      - Downloading Files: API/Users_Guide/Downloading_Files.md
      - Data Analysis: API/Users_Guide/Data_Analysis.md
      - BAM Slicing: API/Users_Guide/BAM_Slicing.md
      - Submission: API/Users_Guide/Submission.md
      - Python Examples: API/Users_Guide/Python_Examples.md
      - GraphQL Examples: API/Users_Guide/GraphQL_Examples.md
      - System Information: API/Users_Guide/System_Information.md
      - Additional Examples: API/Users_Guide/Additional_Examples.md
      - 'Appendix A: Available Fields': API/Users_Guide/Appendix_A_Available_Fields.md
      - 'Appendix B: Key Terms': API/Users_Guide/Appendix_B_Key_Terms.md
      - 'Appendix C: Format of Submission Queries and Responses': API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md
      - Release Notes: API/Release_Notes/API_Release_Notes.md
      - Download PDF: /API/PDF/API_UG.pdf
  - Data Portal:
      - Getting Started: Data_Portal/Users_Guide/getting_started.md
      - Quick Start: Data_Portal/Users_Guide/quick_start.md
      - Tutorial Videos: Data_Portal/Users_Guide/Video_Tutorials.md
      - Cohort Builder: Data_Portal/Users_Guide/cohort_builder.md
      - Analysis Center: Data_Portal/Users_Guide/analysis_center.md
      - Repository: Data_Portal/Users_Guide/Repository.md
      - Projects: Data_Portal/Users_Guide/Projects.md
      - BAM Slicing: Data_Portal/Users_Guide/BAMslicing.md
      - Clinical Data Analysis: Data_Portal/Users_Guide/clinical_data_analysis.md
      - Cohort Comparison: Data_Portal/Users_Guide/cohort_comparison.md
      - Cohort Level MAF: Data_Portal/Users_Guide/cohortMAF.md
      - Gene Expression Clustering: Data_Portal/Users_Guide/gene_expression_clustering.md
      - Mutation Frequency: Data_Portal/Users_Guide/mutation_frequency.md
      - OncoMatrix: Data_Portal/Users_Guide/oncomatrix.md
      - ProteinPaint: Data_Portal/Users_Guide/proteinpaint_lollipop.md
      - scRNA Visualization: Data_Portal/Users_Guide/scRNA.md
      - Sequence Reads: Data_Portal/Users_Guide/proteinpaint_bam.md
      - Set Operations: Data_Portal/Users_Guide/set_operations.md
      - For Developers: Data_Portal/Users_Guide/Developers_Guide.md
      - Release Notes: Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
      - Download PDF: Data_Portal/PDF/Data_Portal_UG.pdf
  - Data Submission:
      - Before Submitting Data to the GDC Portal: Data_Submission_Portal/Users_Guide/Checklist.md
      - Data Submission Overview: Data_Submission_Portal/Users_Guide/Data_Submission_Overview.md
      - Data Submission Portal: Data_Submission_Portal/Users_Guide/Data_Submission_Process.md
      - Data Upload Walkthrough: Data_Submission_Portal/Users_Guide/Data_Submission_Walkthrough.md
      - Submission Best Practices: Data_Submission_Portal/Users_Guide/Best_Practices.md
      - Troubleshooting Guide: Data_Submission_Portal/Users_Guide/Troubleshooting.md
      - Release Notes: Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md
      - Download PDF: Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf
  - Data Transfer Tool:
      - Getting Started: Data_Transfer_Tool/Users_Guide/Getting_Started.md
      - Preparing for Data Download and Upload: Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md
      - Data Transfer Tool Command Line Documentation: Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md
      - Release Notes - Command Line: Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md
      - Data Transfer Tool UI Documentation: Data_Transfer_Tool/Users_Guide/Data_Download_DTT_UI.md
      - Release Notes - UI: Data_Transfer_Tool/Release_Notes/DTT_UI_Release_Notes.md
      - Troubleshooting Guide: Data_Transfer_Tool/Users_Guide/Appendix_B_TroubleShooting.md
      - Download PDF: Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf
  - Data Dictionary:
      - About: Data_Dictionary/index.md
      - Viewer: Data_Dictionary/viewer.md
      - Search: https://gdc-mvs.nci.nih.gov/gdc/" target="_blank" rel="noopener noreferrer
      - Release Notes: Data_Dictionary/Release_Notes/Data_Dictionary_Release_Notes.md
  - Data:
      - Introduction: Data/Introduction.md
      - GDC Data Model: Data/Data_Model/GDC_Data_Model.md
      - Data Security: Data/Data_Security/Data_Security.md
      - 'File Format: MAF': Data/File_Formats/MAF_Format.md
      - 'File Format: VCF': Data/File_Formats/VCF_Format.md
      - 'Bioinformatics Pipeline: DNA-Seq Analysis: Whole Genome Sequencing Variant Calling': Data/Bioinformatics_Pipelines/DNA_Seq_WGS.md
      - 'Bioinformatics Pipeline: DNA-Seq Analysis: Whole Exome and Targeted Sequencing Analysis Pipeline': Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md
      - 'Bioinformatics Pipeline: mRNA Analysis': Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md
      - 'Bioinformatics Pipeline: miRNA Analysis': Data/Bioinformatics_Pipelines/miRNA_Pipeline.md
      - 'Bioinformatics Pipeline: Copy Number Variation Analysis': Data/Bioinformatics_Pipelines/CNV_Pipeline.md
      - 'Bioinformatics Pipeline: Methylation Analysis Pipeline': Data/Bioinformatics_Pipelines/Methylation_Pipeline.md
      - 'Bioinformatics Pipeline: Protein Expression': Data/Bioinformatics_Pipelines/RPPA_intro.md
      - Aligned Reads Summary Metrics: Data/Bioinformatics_Pipelines/Aligned_reads_summary_metrics.md
      - Release Notes: Data/Release_Notes/Data_Release_Notes.md
      - Download PDF: Data/PDF/Data_UG.pdf
  - Encyclopedia:
      - Index: Encyclopedia/index.md
      - ABSOLUTE LiftOver: Encyclopedia/pages/ABSOLUTE_LiftOver.md
      - Affymetrix SNP 6.0: Encyclopedia/pages/Affymetrix_SNP_6.0.md
      - Aggregated Somatic Mutation: Encyclopedia/pages/Aggregated_Somatic_Mutation.md
      - Aligned Reads: Encyclopedia/pages/Aligned_Reads.md
      - Aliquot: Encyclopedia/pages/Aliquot.md
      - Aliquot Ensemble Somatic Variant Merging and Masking: Encyclopedia/pages/Aliquot_Ensemble_Somatic_Variant_Merging_and_Masking.md
      - Analyte: Encyclopedia/pages/Analyte.md
      - Annotations: Encyclopedia/pages/Annotations.md
      - Annotations TCGA: Encyclopedia/pages/Annotations_TCGA.md
      - Arriba: Encyclopedia/pages/Arriba.md
      - ASCAT2: Encyclopedia/pages/ASCAT2.md
      - ASCAT3: Encyclopedia/pages/ASCAT3.md
      - AscatNGS: Encyclopedia/pages/AscatNGS.md
      - BCGSC miRNA Profiling: Encyclopedia/pages/BCGSC_miRNA_Profiling.md
      - Biospecimen Data: Encyclopedia/pages/Biospecimen_Data.md
      - Birdseed: Encyclopedia/pages/Birdseed.md
      - BRASS: Encyclopedia/pages/BRASS.md
      - Cancer Genomics Hub: Encyclopedia/pages/Cancer_Genomics_Hub.md
      - Case: Encyclopedia/pages/Case.md
      - Center for Cancer Genomics: Encyclopedia/pages/Center_for_Cancer_Genomics.md
      - Clinical Data: Encyclopedia/pages/Clinical_Data.md
      - Clinical Supplement: Encyclopedia/pages/Clinical_Supplement.md
      - Controlled Access: Encyclopedia/pages/Controlled_Access.md
      - Data Access Policy: Encyclopedia/pages/Data_Access_Policy.md
      - Data Submitter: Encyclopedia/pages/Data_Submitter.md
      - dbGaP: Encyclopedia/pages/dbGaP.md
      - Entity: Encyclopedia/pages/Entity.md
      - FM Simple Somatic Mutation: Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
      - FoundationOne Annotation: Encyclopedia/pages/FoundationOne_Annotation.md
      - FoundationOne Variant Aggregation and Masking: Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md
      - FPKM-UQ: Encyclopedia/pages/FPKM-UQ.md
      - FPKM: Encyclopedia/pages/FPKM.md
      - GATK4 MuTect2 Tumor-Only: Encyclopedia/pages/GATK4_MuTect2_Tumor-Only.md
      - GATK4 MuTect2 Tumor-Only Annotation: Encyclopedia/pages/GATK4_MuTect2_Tumor-Only_Annotation.md
      - GDC API: Encyclopedia/pages/GDC_API.md
      - GDC Data Portal: Encyclopedia/pages/GDC_Data_Portal.md
      - GDC Data Submission Portal: Encyclopedia/pages/GDC_Data_Submission_Portal.md
      - GDC Data Transfer Tool: Encyclopedia/pages/GDC_Data_Transfer_Tool.md
      - GDC Documentation Site: Encyclopedia/pages/GDC_Documentation_Site.md
      - GDC Web Site: Encyclopedia/pages/GDC_Web_Site.md
      - Genomic Data Analysis Network: Encyclopedia/pages/Genomic_Data_Analysis_Network.md
      - Genomic Data Commons: Encyclopedia/pages/Genomic_Data_Commons.md
      - Harmonized Data: Encyclopedia/pages/Harmonized_Data.md
      - Latest Data: Encyclopedia/pages/Latest_Data.md
      - Manifest File: Encyclopedia/pages/Manifest_File.md
      - MD5 Checksum: Encyclopedia/pages/MD5_Checksum.md
      - MuSE: Encyclopedia/pages/MuSE.md
      - MuSE Annotation: Encyclopedia/pages/MuSE_Annotation.md
      - Mutation Annotation Format: Encyclopedia/pages/Mutation_Annotation_Format.md
      - Mutation Annotation Format TCGAv2: Encyclopedia/pages/Mutation_Annotation_Format_TCGAv2.md
      - MuTect2: Encyclopedia/pages/MuTect2.md
      - MuTect2 Annotation: Encyclopedia/pages/MuTect2_Annotation.md
      - Pindel: Encyclopedia/pages/Pindel.md
      - Pindel Annotation: Encyclopedia/pages/Pindel_Annotation.md
      - Redaction: Encyclopedia/pages/Redaction.md
      - Release Number: Encyclopedia/pages/Release_Number.md
      - REST API: Encyclopedia/pages/REST_API.md
      - RNA-Seq: Encyclopedia/pages/RNA-Seq.md
      - SeSAMe Methylation Beta Estimation: Encyclopedia/pages/SeSAMe_Methylation_Beta_Estimation.md
      - Seurat 10x Chromium: Encyclopedia/pages/Seurat_10x_Chromium.md
      - SNP Array-Based Data: Encyclopedia/pages/SNP_Array-Based_Data.md
      - STAR-Fusion: Encyclopedia/pages/STAR-Fusion.md
      - STAR 2-Pass Chimeric: Encyclopedia/pages/STAR_2-Pass_Chimeric.md
      - STAR 2-Pass Genome: Encyclopedia/pages/STAR_2-Pass_Genome.md
      - STAR 2-Pass Transcriptome: Encyclopedia/pages/STAR_2-Pass_Transcriptome.md
      - STAR Counts: Encyclopedia/pages/STAR_Counts.md
      - TCGA Barcode: Encyclopedia/pages/TCGA_Barcode.md
      - TCGA VCF 1.1v2: Encyclopedia/pages/TCGA_VCF_1.1v2.md
      - TCIA: Encyclopedia/pages/TCIA.md
      - UUID: Encyclopedia/pages/UUID.md
      - Variant Call Format: Encyclopedia/pages/Variant_Call_Format.md
      - Variant Type: Encyclopedia/pages/Variant_Type.md
      - VarScan2: Encyclopedia/pages/VarScan2.md
      - VarScan2 Annotation: Encyclopedia/pages/VarScan2_Annotation.md
      - VCF LiftOver: Encyclopedia/pages/VCF_LiftOver.md
site_name: GDC Docs
site_url: https://docs.gdc.cancer.gov
theme:
  custom_dir: overrides
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  logo: images/nih-header-logo-color.png
  name: material
  palette:
    primary: white
    scheme: gdc-accessible
  plugins:
    - search
